### ISSUE TITLE
Integration not Updating at Specified Interval

### ISSUE THREAD

**Issue by Sirgrant618** [Pirate-Weather/pirate-weather-ha#112]
Hi there,

<img width="561" alt="image" src="https://github.com/alexander0042/pirate-weather-ha/assets/66051139/80fef52f-5c27-4b26-a1e1-d5bf0213643c">

For some reason, Pirate Weather will not grab new data at the specified interval (left at default 1200ms), or ever. I set up the integration last night (Saturday night) and woke up to the integration not updating for 9 hours. Still showed today (sunday) as being 'tomorrow'. The image above is after I I totally removed the integration in Frontend and through HACS. Restarted, etc. Re-added. It will grab new initial data after that, but then wont update at the 20 min mark. 

Am I doing something wrong?

**Comment by harristom** [comment]
Same problem here

**Comment by joshtbernstein** [comment]
I'm having the same issue. It's literally not fetching updates. It shows last updated as 2 days, but you can tell something's wrong since it's still showing the forecast for Wednesday and Thursday (today is Friday).

**Comment by relaystar** [comment]
I have the same problem, the entity created by the integration is just not updating.  It is still showing the weather for yesterday.  I can't see anything in the main home-assistant.log related to pirateweather (other than lines like "[homeassistant.components.weather] Setting up weather.pirateweather")

**Comment by joshtbernstein** [comment]
@alexander0042 Strangely, it started working. I'll keep an eye on it and report back if it reoccurs.

**Comment by sheckandar** [comment]
I noticed the same issue.

The weather updates work for a while after restarting HA, but then at some point just stop. I can tell by looking at the hourly forecasts, they are several hours in the past.

I check the timestamps of the following entities to verify that the issue exists:

{{ as_local(states.sensor.pirateweather_apparent_temperature_0h.last_changed) }}
{{ as_local(states.sensor.pirateweather_apparent_temperature_0h.last_updated) }}
{{ as_local(states.sensor.pirateweatherdaily_apparent_temperature_0h.last_changed) }}

I can force refresh the data by reloading the integration, then it refreshes just once.

There are no errors recorded in the logs related to this integration.

I'm running latest HA and HA OS.

**Comment by sheckandar** [comment]
After upgrading to HA Core 2023.6.3, the problem went away.

**Comment by relaystar** [comment]
FWIW mine started working also.  I can't be sure if this was because of a HA restart or not.

**Comment by martini1992** [comment]
I am also seeing this issue on 2023.6.3 with v1.2
I have enabled debug logging but not seen any yet (only set to update hourly)

**Comment by martini1992** [comment]
Seems to be working ok now, after restarting HA before I enabled debugging. I'll leave it in though and post here again if I see the issue.

**Comment by scarolan** [comment]
Same issue here - weather card is still showing yesterday's conditions and forecast.

**Comment by alexander0042** [comment]
Thanks for the comments, they're really helping to isolate this as a major issue.

I just pushed a new version that makes a couple small changes that I hope help, and also adds some basic logging that should shed some light one where this is getting stuck. If you could let me know if this crops again in the new version (1.2.2), we can go from there

**Comment by ramalamadingdong** [comment]
For me it's sensors not updating at all... Everything else works...

**Comment by alexander0042** [comment]
Thanks for chiming in. @ramalamadingdong, are you on the newest version in HACS, and are you seeing anything in the logs? If you check the info log, there should be a message every time an update should occur

**Comment by ramalamadingdong** [comment]
> Thanks for chiming in. @ramalamadingdong, are you on the newest version in HACS, and are you seeing anything in the logs? If you check the info log, there should be a message every time an update should occur

Actually. The issue is fixed as of last night. Thanks!!

**Comment by ASAujla** [comment]
I can't believe I just found this integration... Great work @alexander0042 

I installed there latest version last night. Update internal set to 1200s. It hasn't updated since, is still showing yesterday's weather.

**Comment by alexander0042** [comment]
Thanks for the kind words @ASAujla, and hopefully we can get to the bottom of this!
Do you mind taking a quick look in the logs and checking if there's anything there from Pirate Weather?

**Comment by ASAujla** [comment]
Hey @alexander0042, thanks for responding. I've checked the logs and then only thing that comes up is the warning about the deprecated method this integrating is currently using:

> custom_components.pirateweather.weather::None is using a forecast attribute on an instance of WeatherEntity, this is deprecated and will be unsupported from Home Assistant 2024.3. Please report it to the custom integration author

I've tried reloading the add-on and hitting "configure" again, but it just won't update.

**Comment by ASAujla** [comment]
Not sure how or why, but I noticed that it has been working since Thursday! @alexander0042 I don't know if you fixed i as I can't remember updating the integration, or whether something wasn't working server-side. Anyway, thanks again!

**Comment by alexander0042** [comment]
This is a really long standing issue that's tricky to pin down; however, I'm hopeful the v1.3 pre-release I pushed this morning will help! It switches to a new approach, using a service update, which I'm thinking may be more reliable. Let me know if you have a chance to give it a try! 

Longer term, I'm planning on submitting this as a built-in integration, which should improve the reliability even more by moving to a true async approach throughout, but that won't be for a few more months, so hoping this approach helps!

**Comment by cloneofghosts** [comment]
Stable version of 1.3 has been released. Try that version and see if it helps with this issue.

**Comment by cloneofghosts** [comment]
Haven't heard anything on this issue since the release of v1.3 so I'm going to close it for now. If it pops up again feel free to comment or open a new issue.
