### ISSUE TITLE
many constants deprecated - list in the issue (will be removed in HA Core 2025.1)

### ISSUE THREAD

**Issue by pejotigrek** [Pirate-Weather/pirate-weather-ha#169]
### Describe the bug

it looks like some constants used by HA are going to be renamed and deprecated next year.

### Expected behavior

constants updated according to HA requirements, so no warnings/errors in log

### Actual behavior

after updating from HA 2023.12 to HA 2024.1.1 many warnings in the log:

```
2024-01-05 22:22:29.391 WARNING (MainThread) [homeassistant.const] LENGTH_MILLIMETERS was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILLIMETERS instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:22:29.405 WARNING (MainThread) [homeassistant.const] PRESSURE_HPA was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.HPA instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:22:29.414 WARNING (MainThread) [homeassistant.const] SPEED_METERS_PER_SECOND was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.METERS_PER_SECOND instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:22:29.423 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:22:30.730 WARNING (MainThread) [homeassistant.const] LENGTH_MILLIMETERS was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILLIMETERS instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:22:30.740 WARNING (MainThread) [homeassistant.const] PRESSURE_MBAR was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.MBAR instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:22:30.751 WARNING (MainThread) [homeassistant.const] SPEED_METERS_PER_SECOND was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.METERS_PER_SECOND instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:22:30.760 WARNING (MainThread) [homeassistant.const] PRESSURE_HPA was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.HPA instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:22:30.771 WARNING (MainThread) [homeassistant.const] PRESSURE_INHG was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.INHG instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:22:30.781 WARNING (MainThread) [homeassistant.const] LENGTH_KILOMETERS was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.KILOMETERS instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:22:30.790 WARNING (MainThread) [homeassistant.const] LENGTH_MILLIMETERS was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILLIMETERS instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:22:30.801 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:22:30.812 WARNING (MainThread) [homeassistant.const] TEMP_FAHRENHEIT was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:26:02.078 WARNING (MainThread) [homeassistant.const] LENGTH_CENTIMETERS was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.CENTIMETERS instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:26:02.107 WARNING (MainThread) [homeassistant.const] LENGTH_INCHES was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.INCHES instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:26:02.128 WARNING (MainThread) [homeassistant.const] LENGTH_KILOMETERS was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.KILOMETERS instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:26:02.154 WARNING (MainThread) [homeassistant.const] LENGTH_MILES was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILES instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:26:02.179 WARNING (MainThread) [homeassistant.const] LENGTH_MILLIMETERS was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILLIMETERS instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:26:02.202 WARNING (MainThread) [homeassistant.const] PRECIPITATION_INCHES was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPrecipitationDepth.INCHES instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:26:02.218 WARNING (MainThread) [homeassistant.const] PRECIPITATION_MILLIMETERS_PER_HOUR was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfVolumetricFlux.MILLIMETERS_PER_HOUR instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:26:02.241 WARNING (MainThread) [homeassistant.const] PRESSURE_MBAR was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.MBAR instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:26:02.260 WARNING (MainThread) [homeassistant.const] SPEED_KILOMETERS_PER_HOUR was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.KILOMETERS_PER_HOUR instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:26:02.281 WARNING (MainThread) [homeassistant.const] SPEED_METERS_PER_SECOND was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.METERS_PER_SECOND instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:26:02.298 WARNING (MainThread) [homeassistant.const] SPEED_MILES_PER_HOUR was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.MILES_PER_HOUR instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:26:02.314 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-01-05 22:26:02.333 WARNING (MainThread) [homeassistant.const] TEMP_FAHRENHEIT was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
```

### Home Assistant version

2024.1.1

### Integration version

v1.3.5

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/), [parameter documentation](https://web.archive.org/web/20230128172320/https://www.home-assistant.io/integrations/weather.darksky/) and [sensor documentation](https://web.archive.org/web/20230326100953/https://www.home-assistant.io/integrations/darksky) before opening this issue.
- [X] I have searched this repository and [Pirate Weather Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have checked to see if the issue is not an API issue.
- [X] I have written an informative title.

**Comment by DaN66O** [comment]
Updated to Integration version v1.3.6
The same warning
```
LENGTH_KILOMETERS was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.KILOMETERS instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
LENGTH_MILLIMETERS was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILLIMETERS instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
TEMP_CELSIUS was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
TEMP_FAHRENHEIT was used from pirateweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
```

**Comment by cloneofghosts** [comment]
Thank you both for the reports. I've gone ahead and released v1.3.7b1 which should fix the warning you are seeing. If there are no issues with the beta version I'll release the stable version in a day or two.

**Comment by DaN66O** [comment]
> Thank you both for the reports. I've gone ahead and released v1.3.7b1 which should fix the warning you are seeing. If there are no issues with the beta version I'll release the stable version in a day or two.
> 
> EDIT: I realized that I had missed some constants in the original beta so I released Beta 2 which should hopefully remove the rest of the warnings.

Version 1.3.7b1 the problem remains.
Version 1.3.7b2 solved the problem.

**Comment by cloneofghosts** [comment]
I realized I missed a few of them when I did my first pass and I also probably released the beta based on the main branch instead of the fixed branch. I have a PR ready for @alexander0042 to review and once that gets merged in the stable version will be released.

**Comment by cloneofghosts** [comment]
Stable version released
